### ISSUE TITLE
Is there a reason for scraping the HTML?

### ISSUE THREAD

**Issue by peakay** [kcinnick/pyredictit#2]
I'm wondering if the point is to better emulate the browser as opposed to reverse engineering their API endpoints.

**Comment by kcinnick** [comment]
Basically, I wanted to write something like this without having to use Selenium.  Both as a personal programming project and because my thought at the time was that using Selenium to essentially recreate what a user would do would cause unnecessary lag time in order execution.  All sorts of things slow down Selenium vs. doing it all with requests.

**Comment by peakay** [comment]
Perhaps I'm misunderstanding the code, but is mechanicalsoup not scraping the HTML? I see that you are basically parsing the HTML table to get contracts / update contracts in some areas where there exist endpoints to do this.

**Comment by kcinnick** [comment]
ahh, sorry - I misunderstood your comment.  I wrote that bit a while ago (the original repo for this project had to be locked due to some less-than-sophisticated credentials management in the script) so I can't say for certain why I made that choice, but if I had to guess it'd be because either those endpoints did not exist at the time, or because the information returned from the API wasn't as complete as the information returned on the site.  I believe it may have been the latter but again, I'm not positive on that.
